### ISSUE TITLE
Color Scheme Files

### ISSUE THREAD

**Issue by OfficiallyBrown** [Trevelopment/MZD-AIO#111]
When I try to complie a set of tweaks that includes "Custom Infotainment Colors" it tells me to download the color scheme first. I clicked download, and then okay and the dialog box went away and just returned to the tweak screen. I pressed Start Compiling again and it just keeps telling me to download the scheme, it even asks to overwrite the files I already have, but refuses to let me compile the tweak

Also quick edit: I installed a few tweaks and after playing with some settings for a bit I turned the car off and went to get out, but the power didnt shut off complely. the speedometer and temp controls are still lit up and when I open the door, the door alarm goes off, even when I tuen the car off

**Comment by Trevelopment** [comment]
This is a problem with the link where the color scheme files are located, I have to fix this.

**Comment by OfficiallyBrown** [comment]
Okay, no worries, just thought I'd open an issue since I couldn't seem to find any mentions of it in the other ones. I also saw that the project is nearing its EOL, so even if it never gets fixed, you've already made me even more happy to have chosen the car I did, so thank you. I'll be making a donation regardless soon, for all the effort you have already put in to this. Escpecially with the recent holiday yesterday ;)

**Comment by madmaninabox42** [comment]
I was having the same issue, is there a manual download we can use instead? Everything else has been pretty seamless.

**Comment by Trevelopment** [comment]
Fixed the link @OfficiallyBrown @madmaninabox42  Will you guys do me a favor and test to make sure I fixed it correctly.

**Comment by madmaninabox42** [comment]
Reinstalled MZD-AIO with a fresh download, still having the same issue it seems.

**Comment by OfficiallyBrown** [comment]
@Trevelopment I'd love to, but im not seeing any new downloads on the page, and the auto updater doesn't seem to think theres anything to update? Unless I'm missing something lol

**Comment by Trevelopment** [comment]
ok I just tested it, so you tried to redownload the files?  Try this, here's where they are located: `C:\Users\{{userName}|}\AppData\Roaming\MZD-AIO-TI\color-schemes` if that exists then delete it but also if you put redownload files it should overwrite that folder anyways

**Comment by Trevelopment** [comment]
If all else fails this is where I put the new link to the zip and you can manually unzip it in that `.../Roaming/MZD-AIO-TI/` location:  hhttps://github.com/Trevelopment/cmu-autorun/releases/download/1/color-schemes.zip

**Comment by OfficiallyBrown** [comment]
I did try, and it's still acting the same, and I also do not have a color-scheme folder in my Roaming folder. I downloaded the .zip^ and that worked.

What I meant was, that there didn't seem to be any updates for the app its self. (Unless you meant that the link was broken from the download server side) I do get an update error when I start the app, but when I check for updates in the Download menu, it doesn't seem to find anything

**Comment by Trevelopment** [comment]
@OfficiallyBrown Thats because the updates were on bintray.com which is been deprecated

**Comment by moodkillah** [comment]
hi, im having the same problem, despite downloading the color scheme zip, the program is not recognizing these files, maybe because the zip provided at the date was outdated? can you upload new color scheme files? thanks

**Comment by fraricci** [comment]
Thanks a lot for this great piece of software!

In case this is still useful today for someone running this app on linux, the directory where to locate the color-schemes folder is:
`/home/your_username/.config/MZD-AIO-TI/`

**Comment by PencilNotPen** [comment]
/Users/YOUR USERNAME/Library/Application Support/MZD-AIO-TI/color-schemes 

If you're on a Mac.

**Comment by troguan** [comment]
Try this route in Windows in case the error occurred that did not detect the COLORs.

C:\Users\my_user\AppData\Roaming\MZD-AIO-TI

Paste in that path, windows
